### ISSUE TITLE
Why should we handle sigint?

### ISSUE THREAD

**Issue by luebken** [giantswarm/giantswarm-firstapp-go#12]
We are handling signals in L52 of main.go:
https://github.com/giantswarm/giantswarm-firstapp-go/blob/master/main.go#L52

Reasoning for being a nice container citizen and stop fast and gracefully. But I know only of the usecase of receiving a `sigterm` in the case of a `docker stop`. When and why would we receive a `sigint`?

**Comment by htr** [comment]
usually a sigint is caused by ctrl-c, so I wouldn't expect it to happen
in this situation (container running in giantswarm)

**Comment by denderello** [comment]
`SIGINT` is another POSIX signal that is mostly received when you press `ctrl-c`. http://en.wikipedia.org/wiki/Unix_signal#POSIX_signals

**Comment by denderello** [comment]
Still it's nice to react on this if you start the container locally using `docker run -it`.

**Comment by luebken** [comment]
Forgot about the local handling. Good point. Thanks for highlighting.
