### ISSUE TITLE
Move from fig to docker-compose

### ISSUE THREAD

**Issue by marians** [giantswarm/giantswarm-firstapp-go#9]
The code uses fig. To be up to date, it should be modified to work with docker-compose.

**Comment by luebken** [comment]
Docker-compose is backwards compatible. It even reads fig.yml by default.

That said the current fig.yml is broken. The preferred way in this repo is to use the Makefile. As a short term fix I will create a PR to remove the fig.yml.

**Comment by luebken** [comment]
I just noticed that there is even a Makefile target `fig-up` which dependency on the cross-compile. But my suggestion would be to remove it anyway since having a fig.yml or docker-compose.yml suggests that a simple `docker-compose up` would work which doesn't.
